version: '3'
services:
    search-handler:
        restart: always
        env_file:
        - .env
        build:
            context: .
        ports:
            - "80:80"
        volumes:
            - ./:/code
            - ./tmp:/code/tmp